# Generated by Django 5.1.3 on 2024-11-12 20:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('last_online', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='SensorsData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('temperature', models.FloatField(default=0.0)),
                ('humidity', models.FloatField(default=0.0)),
                ('moisture', models.FloatField(default=0.0)),
                ('light_intensity', models.FloatField(default=0.0)),
                ('nitrogen', models.FloatField(default=0.0)),
                ('phosphorus', models.FloatField(default=0.0)),
                ('potassium', models.FloatField(default=0.0)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
