# Generated by Django 5.1.3 on 2024-11-12 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorsdata',
            old_name='device_id',
            new_name='device',
        ),
    ]
