# Generated by Django 5.1.3 on 2024-12-27 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalMedicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('active_ingredients', models.JSONField(default=list)),
                ('preparation', models.TextField()),
                ('application_method', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrganicMedicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('active_ingredients', models.JSONField(default=list)),
                ('preparation_steps', models.JSONField(default=list)),
                ('application_method', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('botanical_name', models.CharField(max_length=255)),
                ('common_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=255)),
                ('height', models.JSONField(default=dict)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='easy', max_length=255)),
                ('light', models.CharField(choices=[('Full Sun', 'Full Sun'), ('Partial Sun', 'Partial Sun')], max_length=255)),
                ('alternate_light', models.CharField(choices=[('Full Sun', 'Full Sun'), ('Partial Sun', 'Partial Sun')], max_length=255)),
                ('water_consumption', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=255)),
                ('watering', models.TextField()),
                ('soil_depth', models.JSONField(default=dict)),
                ('seeding_depth', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('seed_spacing', models.JSONField(default=dict)),
                ('germination_time', models.JSONField(default=dict)),
                ('optimal_germination_temperature', models.JSONField(default=dict)),
                ('growth_time', models.JSONField(default=dict)),
                ('recommended_temperature', models.JSONField(default=dict)),
                ('image_urls', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('bacterial', 'Bacterial'), ('fungal', 'Fungal'), ('viral', 'Viral'), ('parasitic', 'Parasitic')], max_length=255)),
                ('description', models.TextField()),
                ('spread', models.TextField()),
                ('symptoms', models.JSONField(blank=True, default=list)),
                ('causes', models.JSONField(blank=True, default=list)),
                ('cultural_control', models.JSONField(default=list)),
                ('prevention', models.JSONField(blank=True, default=list)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('chemical_control', models.ManyToManyField(to='guide_views.chemicalmedicine')),
                ('organic_control', models.ManyToManyField(to='guide_views.organicmedicine')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseRecommendedAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.JSONField(default=list)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide_views.disease')),
                ('recommended_chemical_medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guide_views.chemicalmedicine')),
                ('recommended_organic_medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guide_views.organicmedicine')),
            ],
        ),
        migrations.CreateModel(
            name='PlantDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide_views.disease')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide_views.plant')),
            ],
        ),
    ]
