# Generated by Django 5.1.3 on 2024-12-28 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalControl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('active_ingredients', models.JSONField(default=list)),
                ('preparation_methods', models.TextField(default='Check product label for preparation instructions.')),
                ('application_methods', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='OrganicControl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('active_ingredients', models.JSONField(default=list)),
                ('preparation_steps', models.JSONField(default=list)),
                ('application_methods', models.JSONField(default=list)),
            ],
        ),
        migrations.AlterField(
            model_name='disease',
            name='chemical_control',
            field=models.ManyToManyField(to='guide_views.chemicalcontrol'),
        ),
        migrations.AlterField(
            model_name='diseaserecommendedaction',
            name='recommended_chemical_medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guide_views.chemicalcontrol'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='organic_control',
            field=models.ManyToManyField(to='guide_views.organiccontrol'),
        ),
        migrations.AlterField(
            model_name='diseaserecommendedaction',
            name='recommended_organic_medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guide_views.organiccontrol'),
        ),
        migrations.DeleteModel(
            name='ChemicalMedicine',
        ),
        migrations.DeleteModel(
            name='OrganicMedicine',
        ),
    ]
