from rest_framework import serializers

class DiseaseSerializer(serializers.Serializer):
    _id = serializers.CharField(read_only=True)
    name = serializers.CharField(max_length=100)
    small_description = serializers.CharField()
    reasons = serializers.CharField()
    spread = serializers.CharField()
    imgs_urls = serializers.ListField(child=serializers.URLField())
    symptoms = serializers.ListField(child=serializers.CharField())
    cultural = serializers.ListField(child=serializers.CharField())
    conventional = serializers.ListField(child=serializers.CharField())
    organic = serializers.ListField(child=serializers.CharField())
    biological = serializers.ListField(child=serializers.CharField())
    prevention = serializers.ListField(child=serializers.CharField())

class PlantSerializer(serializers.Serializer):
    _id = serializers.CharField(read_only=True)
    name = serializers.CharField(max_length=100)
    botanical_name = serializers.CharField(max_length=100)
    type = serializers.CharField(max_length=50)
    description = serializers.CharField()
    soil_depth = serializers.CharField()
    seeding_depth = serializers.CharField()
    seed_spacing = serializers.CharField()
    watering = serializers.CharField()
    water_consumption = serializers.CharField()
    light = serializers.CharField()
    alternative_light = serializers.CharField()
    height = serializers.DictField(child=serializers.IntegerField())
    optimal_germination_temperature = serializers.DictField(child=serializers.IntegerField())
    germination_time = serializers.CharField()
    growth_time = serializers.CharField()
    difficulty = serializers.CharField()
    recommended_fertilizers = serializers.ListField(child=serializers.CharField())
    fertilizing_rate = serializers.DictField(child=serializers.CharField())
    recommended_temperature_range = serializers.DictField(child=serializers.IntegerField())
    recommended_soil_type = serializers.CharField()
    season = serializers.ListField(child=serializers.CharField(), required=False)
    associated_diseases = serializers.ListField(child=serializers.CharField(), required=False)
    images_urls = serializers.ListField(child=serializers.URLField())
